### ISSUE TITLE
Node warning while building : No Licence 

### ISSUE THREAD

**Issue by mukteshkrmishra** [spring-projects/spring-flo#1]
While trying to execute npm install it throws an warning:

npm WARN Spring-Flo@0.0.1 No license field.

Looks like we need to include "licence":"UNLICENSED" in package.json, atleast to omit this warning.

**Comment by mukteshkrmishra** [comment]
@BoykoAlex , @aclement 
 I was trying to raise a PR. But looks like I do not have permission. Can you please help.

**Comment by BoykoAlex** [comment]
We have added licensing to package.json with this commit e78ebe7e58d0233ab208f53eecc695866917dd52. Hope it will make that warning go away.

**Comment by mukteshkrmishra** [comment]
Working fine.
