### ISSUE TITLE
Palette subscribes to metamodel with undefined listener

### ISSUE THREAD

**Issue by acrisci** [spring-projects/spring-flo#13]
Hi,

I'm getting an error where the palette subscribes to my metamodel with an undefined listener.

I think the `_metamodelListener` private member of the `Palette` is never instantiated but I'm not sure.

https://github.com/spring-projects/spring-flo/blob/master/src/lib/src/palette/palette.component.ts#L101

```
  private _metamodelListener : Flo.MetamodelListener;
```

**Comment by BoykoAlex** [comment]
Yes, you're right this part is somewhat undeveloped since that listening mechanism is not used by our client app... I'm a bit tied up with other things, but think that this could work:
```
  private _metamodelListener : Flo.MetamodelListener = {
    metadataError: (data) => {},
    metadataAboutToChange: () => {},
    metadataChanged: (data) => this.rebuildPalette();
  };
```
If that works for you feel free to submit a PR I'll make sure it's merged.

**Comment by acrisci** [comment]
Ok, I will probably work on that this weekend.

My use case is that I want to dynamically update the palette contents on UI events.

**Comment by BoykoAlex** [comment]
@acrisci do you mind signing the CLA agreement? https://cla.pivotal.io/ I shouyld have asked you that before accepting the PR, but forgot about it. Can you sign it please?

**Comment by acrisci** [comment]
Sure just signed it.
