### ISSUE TITLE
Improve default transition link experience

### ISSUE THREAD

**Issue by sabbyanandan** [spring-projects/spring-flo#26]

**Comment by aclement** [comment]
The DSL before the state is:

```
<extractDB: timestamp || extractFiles: timestamp> && merge: timestamp && cleanse: timestamp && <writetohdfs: timestamp || transform: timestamp && writetos3: timestamp 1->s3jdbc && ss: s3jdbc>
```

then you change the transition condition on writetos3>ss such that it is conditional (condition is ‘2’) then you are left with no default link from writetos3>END.  The link will appear if you touch the text in the DSL text edit window.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow-ui#804
