### ISSUE TITLE
throwing aot compilation errors when included in external project 

### ISSUE THREAD

**Issue by hakhan88** [spring-projects/spring-flo#55]
three errors below are causing the AOT built to fail when AOT is enabled. 

1. ERROR in node_modules\spring-flo\out-tsc\spring-flo.d.ts.EditorComponent.html(12,9): : Directive ResizerDirective, Property 'startDrag' is private and only accessible within class 'ResizerDirective'.

2. node_modules\spring-flo\out-tsc\spring-flo.d.ts.DynamicFormPropertyComponent.html(30,21): : Property 'options' does not exist on type 'ControlModel<any>'.

3. node_modules\spring-flo\out-tsc\spring-flo.d.ts.DynamicFormPropertyComponent.html(34,48): : Property 'language' does not exist on type 'ControlModel<any>'.

suggestions: 
1. make startDrag public rather than private
2. access 'options' as object['options'] rather than object.options
3. access 'options' as object['language'] rather than object.language

please let me know should you require more info on this issue 

thanks

**Comment by BoykoAlex** [comment]
Flo is always included in external projects as it is just a lib. It's included in https://github.com/spring-cloud/spring-cloud-dataflow-ui and works fine as far as I know.
How are you making a dependency on Flo?

**Comment by hakhan88** [comment]
"spring-flo": "0.8.9", including this in the package of the project and building it with AOT enabled

**Comment by BoykoAlex** [comment]
@hakhan88 any chance you can create a PR for the change you'd like?

**Comment by hakhan88** [comment]
ok i'll submit a fix for this. thanks
