### ISSUE TITLE
Support load event ?

### ISSUE THREAD

**Issue by junwang1216** [spring-projects/spring-flo#58]
How do I know that the graph has been loaded?

**Comment by BoykoAlex** [comment]
Yup'd have to elaborate a bit on your question... There are a few EventEmmiters you could subscribe to  get info when the palette is ready, when graph -> text conversion completed, text -> graph conversion completed also when metamodel for the graph has loaded (a promise)... It depends what you'd like to accomplish

**Comment by junwang1216** [comment]
> Yuo'd have to elaborate a bit on your question... There are a few EventEmmiters you could subscribe to get info when the palette is ready, when graph -> text conversion completed, text -> graph conversion completed also when metamodel for the graph has loaded (a promise)... It depends what you'd like to accomplish

when graph -> text conversion completed？

**Comment by junwang1216** [comment]
> Yuo'd have to elaborate a bit on your question... There are a few EventEmmiters you could subscribe to get info when the palette is ready, when graph -> text conversion completed, text -> graph conversion completed also when metamodel for the graph has loaded (a promise)... It depends what you'd like to accomplish

when text -> graph conversion completed ?

**Comment by BoykoAlex** [comment]
You should have `Flo.EditorContext` object available somewhere... See sample app: https://github.com/spring-projects/spring-flo/blob/master/src/demo/app/app.component.ts#L23

`Flo.EditorContext` should have `textToGraphConversionObservable` to which you could subscribe to track when text -> graph conversion is completed.
