### ISSUE TITLE
runtime services?

### ISSUE THREAD

**Issue by ssatguru** [spring-projects/spring-flo#6]
In addition to the three services -metamodel, render and editor should there be a "runtime" service too -  for flow deployment, run time status, persistence etc?

**Comment by BoykoAlex** [comment]
Hmm... possibly deployment and runtime status may become services if there is enough demand. Otherwise you should be able to show status with decorations on nodes and links... Persistence is up to the backend and unlikely to become part of a runtime service... Perhaps these 3 features may be offered via a service just for the convenience purposes, but it hasn't been discussed at all at the moment.

**Comment by ssatguru** [comment]
I needed this for my project so I started coding something myself. Very basic for now. The client app  would provide a runtime service (example : runtime-service-name="SampleRuntimeService") with following function implementation 
deployFlo()
getFloStatus()
loadFlo()
saveFlo()
saveFloAs()
delFlo()
See [https://github.com/ssatguru/spring-flo](https://github.com/ssatguru/spring-flo) 
Sample client
[https://github.com/ssatguru/camel-flo-client](https://github.com/ssatguru/camel-flo-client)

Probably not the best approach.
How would you approach this ?

**Comment by BoykoAlex** [comment]
`load()` and 'save()` I would have done via the DSL text on the backend. Save takes current DSL text and POSTs it to a storing endpoint. Load would be a GET request the response to which is DSL text that you assign to `$scope.definition.text` i think
What would `deployFlo()` do and `getFloStatus()`?
It feels like you want to place buttons on the toolbar that execute these actions. Is that correct? If yes, I doubt you'd need a `runtime` service.
Please see https://github.com/spring-cloud/spring-cloud-dataflow-ui/tree/master/ui/app/scripts/stream. Namely `controllers/create.js` and `views/create-stream.html` that should explain how save can be done. Load is done in a different place in `views/definitions.html` search for `flo-editor` see where DSL text is assigned to scope variable.
