### ISSUE TITLE
Error `Reduce of empty array with no initial value`

### ISSUE THREAD

**Issue by oodamien** [spring-projects/spring-flo#60]
![image](https://user-images.githubusercontent.com/487067/64164329-52df3000-ce43-11e9-855a-f66ba9ce36e2.png)

**Comment by BoykoAlex** [comment]
This is coming from Flo integration into SCDF UI. Moving to SCDF UI: https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1289
