### ISSUE TITLE
Build failing when working with strict mode

### ISSUE THREAD

**Issue by JerinJ** [spring-projects/spring-flo#65]
When `tsconfig.json` has strict mode on, when doing `ng serve` spring-flow dependencies throws error for code-mirror and Model

![image](https://user-images.githubusercontent.com/2240674/74821111-1f2c8f80-5329-11ea-8cf6-cbdfd2daa794.png)

![image](https://user-images.githubusercontent.com/2240674/74826703-12f90000-5332-11ea-9d64-2f84d16228ea.png)

What can be done here.

**Comment by JerinJ** [comment]
I got a fix!!!!

![image](https://user-images.githubusercontent.com/2240674/74826915-6a976b80-5332-11ea-8b80-fa49934a236c.png)

Add lib-check-skip: true
    "skipDefaultLibCheck": true,
    "skipLibCheck": true

**Comment by BoykoAlex** [comment]
@JerinJ we've upgraded Flo to Angular 9 and used **ng-packagr** to build Flo with Ivy compiler. It's in branch **angular9-plus**. Wonder if you could give it a try and see if you get any problems (like the above reported) with that branch. Thanks in advance.
