### ISSUE TITLE
Provide Flo as Node (NPM) Module

### ISSUE THREAD

**Issue by ghillert** [spring-projects/spring-flo#7]
In order to get rid of Bower in SCDF UI, we need to be able to consume Flow as node module. At least initially Flo does not need to be in the NPM repo (Eventually it would be good though). As long as I can consume Flow via GitHub (have the respective `package.json` file) things will be good.

**Comment by BoykoAlex** [comment]
Hopefully addressed with ce73abbca1c8c65af92d0a9bdb8ebc20a2ea86e5
