### ISSUE TITLE
Unexpected logic during filtering

### ISSUE THREAD

**Issue by WolfMeister** [spring-projects/spring-flo#75]
During development based on Spring Flo library, I've faced an unexpected behavior during filtering by name or group.

Here is the explanation:

1. You have an application named **timestamp**. If you'll try to filter by name with values **timestamp** or **Timestamp** you'll see an expected result.
2. But, if you have at least 1 capital letter in the name of the application [e.g. **Timestamp**] and you'll try to filter either by **timestamp** or **Timestamp**  you'll get a _No results found_ message.

Is this an expected behavior designed by the development team or I can submit a pull request regarding this problem?

**Comment by BoykoAlex** [comment]
Feel free to submit a PR and sign the CLA and it'll get reviewed and merged

**Comment by WolfMeister** [comment]
Issue resolved in pull request #76.
